/**

 * Generated from AsyncAPI spec: User Service API v1.0.0

 * Example AsyncAPI v3 specification for testing maxzilla-async-gen

 * Generated by maxzilla-async-gen

 */


/**
 * User entity
 */
export interface User {
  /** Unique user identifier */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  firstName?: string;
  /** User last name */
  lastName?: string;
  /** User role */
  role?: 'admin' | 'user' | 'moderator';
  /** Timestamp when user was created */
  createdAt: string;
  [key: string]: any;
}

/**
 * User update payload
 */
export interface UserUpdate {
  /** User ID being updated */
  id: string;
  /** Fields that were updated */
  updatedFields: UserUpdateUpdatedFields;
  [key: string]: any;
}

interface UserUpdateUpdatedFields {
  email?: string;
  firstName?: string;
  lastName?: string;
  role?: 'admin' | 'user' | 'moderator';
  [key: string]: any;
}

/**
 * Standard message headers
 */
export interface MessageHeaders {
  /** Unique identifier for message correlation */
  correlationId: string;
  /** Message timestamp */
  timestamp: string;
  /** Message source service */
  source?: string;
  [key: string]: any;
}

export type UserCreatedPayload = User;

export type UserCreatedHeaders = MessageHeaders;

/**
 * Event published when a new user is created
 */
export interface UserCreatedMessage {
  payload: UserCreatedPayload;
  headers?: UserCreatedHeaders;
}

export type UserUpdatedPayload = UserUpdate;

export type UserUpdatedHeaders = MessageHeaders;

/**
 * Event published when a user is updated
 */
export interface UserUpdatedMessage {
  payload: UserUpdatedPayload;
  headers?: UserUpdatedHeaders;
}

export type UserCreatedReceiveMessages = UserCreatedMessage;

export type UserUpdatedSendMessages = UserUpdatedMessage;